/**
 * Audio Synthesizer & Speech Player for Mingalar Voice Banking Copilot.
 * Plays WAV audio generated by the configured Burmese TTS service.
 */

import { synthesizeSpeech } from '../api/client';

type PlaybackCallback = (progress: number, isPlaying: boolean) => void;

class BurmeseAudioSynthesizer {
  private currentUtterance: SpeechSynthesisUtterance | null = null;
  private currentAudio: HTMLAudioElement | null = null;
  private audioUrl: string | null = null;
  private isPlaying: boolean = false;
  private isPaused: boolean = false;
  private audioContext: AudioContext | null = null;
  private timerId: number | null = null;
  private listeners: Set<PlaybackCallback> = new Set();
  private durationSeconds: number = 0;
  private elapsedSeconds: number = 0;

  constructor() {
    // AudioContext will be lazily initialized on first user interaction
  }

  private initAudioContext() {
    if (!this.audioContext && typeof window !== 'undefined') {
      const AudioContextClass = window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
      if (AudioContextClass) {
        this.audioContext = new AudioContextClass();
      }
    }
  }

  public subscribe(callback: PlaybackCallback) {
    this.listeners.add(callback);
    return () => {
      this.listeners.delete(callback);
    };
  }

  private notify(progress: number, playing: boolean) {
    this.isPlaying = playing;
    this.listeners.forEach((cb) => cb(progress, playing));
  }

  /** Request and play Burmese speech from the server-side TTS integration. */
  public async speak(
    text: string,
    options: {
      speed?: number;
      personality?: 'friendly' | 'calm' | 'professional';
      onStart?: () => void;
      onEnd?: () => void;
    } = {}
  ): Promise<void> {
    this.stop();
    const cleanText = text.replace(/[\n*#`_]/g, ' ').trim();
    if (!cleanText) return;

    try {
      const audioBlob = await synthesizeSpeech(cleanText);
      this.audioUrl = URL.createObjectURL(audioBlob);
      const audio = new Audio(this.audioUrl);
      this.currentAudio = audio;
      audio.playbackRate = options.speed || 1;
      audio.onloadedmetadata = () => {
        this.durationSeconds = Number.isFinite(audio.duration) ? audio.duration : 0;
      };
      audio.onplay = () => {
        if (this.elapsedSeconds === 0) options.onStart?.();
        this.notify(audio.duration ? audio.currentTime / audio.duration : 0, true);
      };
      audio.ontimeupdate = () => {
        this.elapsedSeconds = audio.currentTime;
        this.notify(audio.duration ? audio.currentTime / audio.duration : 0, true);
      };
      audio.onended = () => {
        this.notify(1, false);
        options.onEnd?.();
        this.releaseAudio();
      };
      audio.onerror = () => {
        this.notify(0, false);
        this.releaseAudio();
      };
      await audio.play();
    } catch {
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
        try {
          window.speechSynthesis.cancel();
          const utterance = new SpeechSynthesisUtterance(cleanText);
          this.currentUtterance = utterance;
          utterance.lang = 'my-MM';
          utterance.rate = options.speed || 1;
          utterance.onstart = () => {
            options.onStart?.();
            this.notify(0, true);
          };
          utterance.onend = () => {
            this.notify(1, false);
            options.onEnd?.();
            this.currentUtterance = null;
          };
          utterance.onerror = () => {
            this.notify(0, false);
            this.currentUtterance = null;
          };
          window.speechSynthesis.speak(utterance);
          return;
        } catch {
          // Fall back to notification reset
        }
      }
      this.notify(0, false);
    }
  }

  private startProgressTicker(duration: number, onComplete?: () => void) {
    this.stopProgressTicker();
    const intervalMs = 100;
    const totalSteps = (duration * 1000) / intervalMs;
    let step = 0;

    this.notify(0, true);

    this.timerId = window.setInterval(() => {
      if (this.isPaused) return;

      step++;
      const progress = Math.min(1, step / totalSteps);
      this.elapsedSeconds = (step * intervalMs) / 1000;
      this.notify(progress, true);

      if (progress >= 1) {
        this.stopProgressTicker();
        this.notify(1, false);
        onComplete?.();
      }
    }, intervalMs);
  }

  private stopProgressTicker() {
    if (this.timerId !== null) {
      clearInterval(this.timerId);
      this.timerId = null;
    }
  }

  private playSimulatedVoice(duration: number, onComplete?: () => void) {
    this.startProgressTicker(duration, onComplete);
    // Produce soft melodic harmonics using AudioContext
    if (this.audioContext && this.audioContext.state !== 'suspended') {
      try {
        const osc = this.audioContext.createOscillator();
        const gain = this.audioContext.createGain();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(440, this.audioContext.currentTime);
        // Soft modulation
        gain.gain.setValueAtTime(0.01, this.audioContext.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.0001, this.audioContext.currentTime + duration);
        osc.connect(gain);
        gain.connect(this.audioContext.destination);
        osc.start();
        osc.stop(this.audioContext.currentTime + duration);
      } catch {
        // Ignored
      }
    }
  }

  public pause() {
    if (this.isPlaying && !this.isPaused) {
      this.isPaused = true;
      this.currentAudio?.pause();
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
        window.speechSynthesis.pause();
      }
      this.notify(this.elapsedSeconds / (this.durationSeconds || 1), false);
    }
  }

  public resume() {
    if (this.isPaused) {
      this.isPaused = false;
      void this.currentAudio?.play();
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
        window.speechSynthesis.resume();
      }
      this.notify(this.elapsedSeconds / (this.durationSeconds || 1), true);
    }
  }

  public stop() {
    this.isPlaying = false;
    this.isPaused = false;
    this.stopProgressTicker();
    this.currentAudio?.pause();
    this.currentAudio = null;
    this.releaseAudio();
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      try {
        window.speechSynthesis.cancel();
      } catch {
        // Ignored
      }
    }
    this.notify(0, false);
  }

  private releaseAudio() {
    if (this.audioUrl) URL.revokeObjectURL(this.audioUrl);
    this.audioUrl = null;
  }

  public getPlaybackState() {
    return {
      isPlaying: this.isPlaying,
      isPaused: this.isPaused,
      duration: this.durationSeconds,
      elapsed: this.elapsedSeconds
    };
  }
}

export const audioSynthesizer = new BurmeseAudioSynthesizer();
